#############################################################################
# Makefile for building: Hotels
# Generated by qmake (3.1) (Qt 6.1.1)
# Project:  Hotels.pro
# Template: subdirs
# Command: D:\qt\6.1.1\mingw81_64\bin\qmake.exe -o Makefile Hotels.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug"
#############################################################################

MAKEFILE      = Makefile

EQ            = =

first: make_first
QMAKE         = D:\qt\6.1.1\mingw81_64\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = copy /y
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = copy /y
INSTALL_PROGRAM = copy /y
INSTALL_DIR   = xcopy /s /q /y /i
QINSTALL      = D:\qt\6.1.1\mingw81_64\bin\qmake.exe -install qinstall
QINSTALL_PROGRAM = D:\qt\6.1.1\mingw81_64\bin\qmake.exe -install qinstall -exe
DEL_FILE      = del
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = move
IDC           = idc
IDL           = midl
ZIP           = zip -r -9
DEF_FILE      = 
RES_FILE      = 
SED           = $(QMAKE) -install sed
MOVE          = move
SUBTARGETS    =  \
		sub-InformationHotels \
		sub-objects


sub-InformationHotels-qmake_all:  FORCE
	@if not exist InformationHotels\ mkdir InformationHotels\ & if not exist InformationHotels\ exit 1
	cd InformationHotels\ && $(QMAKE) -o Makefile D:\projects\Hotels\InformationHotels\InformationHotels.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug"
	cd InformationHotels\ && $(MAKE) -f Makefile qmake_all
sub-InformationHotels: FORCE
	@if not exist InformationHotels\ mkdir InformationHotels\ & if not exist InformationHotels\ exit 1
	cd InformationHotels\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\projects\Hotels\InformationHotels\InformationHotels.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile
sub-InformationHotels-make_first: FORCE
	@if not exist InformationHotels\ mkdir InformationHotels\ & if not exist InformationHotels\ exit 1
	cd InformationHotels\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\projects\Hotels\InformationHotels\InformationHotels.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile 
sub-InformationHotels-all: FORCE
	@if not exist InformationHotels\ mkdir InformationHotels\ & if not exist InformationHotels\ exit 1
	cd InformationHotels\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\projects\Hotels\InformationHotels\InformationHotels.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile all
sub-InformationHotels-clean: FORCE
	@if not exist InformationHotels\ mkdir InformationHotels\ & if not exist InformationHotels\ exit 1
	cd InformationHotels\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\projects\Hotels\InformationHotels\InformationHotels.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile clean
sub-InformationHotels-distclean: FORCE
	@if not exist InformationHotels\ mkdir InformationHotels\ & if not exist InformationHotels\ exit 1
	cd InformationHotels\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\projects\Hotels\InformationHotels\InformationHotels.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile distclean
sub-InformationHotels-install_subtargets: FORCE
	@if not exist InformationHotels\ mkdir InformationHotels\ & if not exist InformationHotels\ exit 1
	cd InformationHotels\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\projects\Hotels\InformationHotels\InformationHotels.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile install
sub-InformationHotels-uninstall_subtargets: FORCE
	@if not exist InformationHotels\ mkdir InformationHotels\ & if not exist InformationHotels\ exit 1
	cd InformationHotels\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\projects\Hotels\InformationHotels\InformationHotels.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile uninstall
sub-objects-qmake_all:  FORCE
	@if not exist objects\ mkdir objects\ & if not exist objects\ exit 1
	cd objects\ && $(QMAKE) -o Makefile D:\projects\Hotels\objects\objects.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug"
	cd objects\ && $(MAKE) -f Makefile qmake_all
sub-objects: FORCE
	@if not exist objects\ mkdir objects\ & if not exist objects\ exit 1
	cd objects\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\projects\Hotels\objects\objects.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile
sub-objects-make_first: FORCE
	@if not exist objects\ mkdir objects\ & if not exist objects\ exit 1
	cd objects\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\projects\Hotels\objects\objects.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile 
sub-objects-all: FORCE
	@if not exist objects\ mkdir objects\ & if not exist objects\ exit 1
	cd objects\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\projects\Hotels\objects\objects.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile all
sub-objects-clean: FORCE
	@if not exist objects\ mkdir objects\ & if not exist objects\ exit 1
	cd objects\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\projects\Hotels\objects\objects.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile clean
sub-objects-distclean: FORCE
	@if not exist objects\ mkdir objects\ & if not exist objects\ exit 1
	cd objects\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\projects\Hotels\objects\objects.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile distclean
sub-objects-install_subtargets: FORCE
	@if not exist objects\ mkdir objects\ & if not exist objects\ exit 1
	cd objects\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\projects\Hotels\objects\objects.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile install
sub-objects-uninstall_subtargets: FORCE
	@if not exist objects\ mkdir objects\ & if not exist objects\ exit 1
	cd objects\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\projects\Hotels\objects\objects.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile uninstall

Makefile: Hotels.pro ../../qt/6.1.1/mingw81_64/mkspecs/win32-g++/qmake.conf ../../qt/6.1.1/mingw81_64/mkspecs/features/spec_pre.prf \
		../../qt/6.1.1/mingw81_64/mkspecs/features/device_config.prf \
		../../qt/6.1.1/mingw81_64/mkspecs/common/sanitize.conf \
		../../qt/6.1.1/mingw81_64/mkspecs/common/gcc-base.conf \
		../../qt/6.1.1/mingw81_64/mkspecs/common/g++-base.conf \
		../../qt/6.1.1/mingw81_64/mkspecs/features/win32/windows_vulkan_sdk.prf \
		../../qt/6.1.1/mingw81_64/mkspecs/common/windows-vulkan.conf \
		../../qt/6.1.1/mingw81_64/mkspecs/common/g++-win32.conf \
		../../qt/6.1.1/mingw81_64/mkspecs/common/windows-desktop.conf \
		../../qt/6.1.1/mingw81_64/mkspecs/qconfig.pri \
		../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_ext_freetype.pri \
		../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_ext_libpng.pri \
		../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_core.pri \
		../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_core_private.pri \
		../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_dbus.pri \
		../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_designer.pri \
		../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_entrypoint_private.pri \
		../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_gui.pri \
		../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_help.pri \
		../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_help_private.pri \
		../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_labsanimation.pri \
		../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_labsanimation_private.pri \
		../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_labssettings.pri \
		../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_labssettings_private.pri \
		../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_labssharedimage.pri \
		../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_linguist.pri \
		../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_linguist_private.pri \
		../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_network.pri \
		../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_network_private.pri \
		../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_opengl.pri \
		../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_openglwidgets.pri \
		../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_qml.pri \
		../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_qmldom_private.pri \
		../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_qmlmodels.pri \
		../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_quick.pri \
		../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_quicklayouts.pri \
		../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_sql.pri \
		../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_svg.pri \
		../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_svgwidgets.pri \
		../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_testlib.pri \
		../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_tools_private.pri \
		../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_uitools.pri \
		../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_widgets.pri \
		../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_xml.pri \
		../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_zlib_private.pri \
		../../qt/6.1.1/mingw81_64/mkspecs/features/qt_functions.prf \
		../../qt/6.1.1/mingw81_64/mkspecs/features/qt_config.prf \
		../../qt/6.1.1/mingw81_64/mkspecs/win32-g++/qmake.conf \
		../../qt/6.1.1/mingw81_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../qt/6.1.1/mingw81_64/mkspecs/features/exclusive_builds.prf \
		../../qt/6.1.1/mingw81_64/mkspecs/features/toolchain.prf \
		../../qt/6.1.1/mingw81_64/mkspecs/features/default_pre.prf \
		../../qt/6.1.1/mingw81_64/mkspecs/features/win32/default_pre.prf \
		../../qt/6.1.1/mingw81_64/mkspecs/features/resolve_config.prf \
		../../qt/6.1.1/mingw81_64/mkspecs/features/exclusive_builds_post.prf \
		../../qt/6.1.1/mingw81_64/mkspecs/features/default_post.prf \
		../../qt/6.1.1/mingw81_64/mkspecs/features/qml_debug.prf \
		../../qt/6.1.1/mingw81_64/mkspecs/features/entrypoint.prf \
		../../qt/6.1.1/mingw81_64/mkspecs/features/precompile_header.prf \
		../../qt/6.1.1/mingw81_64/mkspecs/features/warn_on.prf \
		../../qt/6.1.1/mingw81_64/mkspecs/features/qmake_use.prf \
		../../qt/6.1.1/mingw81_64/mkspecs/features/file_copies.prf \
		../../qt/6.1.1/mingw81_64/mkspecs/features/win32/windows.prf \
		../../qt/6.1.1/mingw81_64/mkspecs/features/testcase_targets.prf \
		../../qt/6.1.1/mingw81_64/mkspecs/features/exceptions.prf \
		../../qt/6.1.1/mingw81_64/mkspecs/features/yacc.prf \
		../../qt/6.1.1/mingw81_64/mkspecs/features/lex.prf \
		Hotels.pro
	$(QMAKE) -o Makefile Hotels.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug"
../../qt/6.1.1/mingw81_64/mkspecs/features/spec_pre.prf:
../../qt/6.1.1/mingw81_64/mkspecs/features/device_config.prf:
../../qt/6.1.1/mingw81_64/mkspecs/common/sanitize.conf:
../../qt/6.1.1/mingw81_64/mkspecs/common/gcc-base.conf:
../../qt/6.1.1/mingw81_64/mkspecs/common/g++-base.conf:
../../qt/6.1.1/mingw81_64/mkspecs/features/win32/windows_vulkan_sdk.prf:
../../qt/6.1.1/mingw81_64/mkspecs/common/windows-vulkan.conf:
../../qt/6.1.1/mingw81_64/mkspecs/common/g++-win32.conf:
../../qt/6.1.1/mingw81_64/mkspecs/common/windows-desktop.conf:
../../qt/6.1.1/mingw81_64/mkspecs/qconfig.pri:
../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_ext_freetype.pri:
../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_ext_libpng.pri:
../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_concurrent.pri:
../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_core.pri:
../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_core_private.pri:
../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_dbus.pri:
../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_designer.pri:
../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_designer_private.pri:
../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_entrypoint_private.pri:
../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_fb_support_private.pri:
../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_gui.pri:
../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_gui_private.pri:
../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_help.pri:
../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_help_private.pri:
../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_labsanimation.pri:
../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_labsanimation_private.pri:
../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_labsfolderlistmodel.pri:
../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri:
../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_labsqmlmodels.pri:
../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_labsqmlmodels_private.pri:
../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_labssettings.pri:
../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_labssettings_private.pri:
../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_labssharedimage.pri:
../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_labssharedimage_private.pri:
../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_labswavefrontmesh.pri:
../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri:
../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_linguist.pri:
../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_linguist_private.pri:
../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_network.pri:
../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_network_private.pri:
../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_opengl.pri:
../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_openglwidgets.pri:
../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_openglwidgets_private.pri:
../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_printsupport.pri:
../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_qml.pri:
../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_qml_private.pri:
../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_qmlcompiler_private.pri:
../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_qmldom_private.pri:
../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_qmllocalstorage.pri:
../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_qmllocalstorage_private.pri:
../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_qmlmodels.pri:
../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_qmlmodels_private.pri:
../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_qmltest.pri:
../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_qmlworkerscript.pri:
../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_quick.pri:
../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_quick_private.pri:
../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_quickcontrols2impl.pri:
../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri:
../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_quicklayouts.pri:
../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_quicklayouts_private.pri:
../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_quickshapes_private.pri:
../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_quicktemplates2.pri:
../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_sql.pri:
../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_sql_private.pri:
../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_svg.pri:
../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_svg_private.pri:
../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_svgwidgets.pri:
../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_svgwidgets_private.pri:
../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_testlib.pri:
../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_tools_private.pri:
../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_uitools.pri:
../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_widgets.pri:
../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_xml.pri:
../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_xml_private.pri:
../../qt/6.1.1/mingw81_64/mkspecs/modules/qt_lib_zlib_private.pri:
../../qt/6.1.1/mingw81_64/mkspecs/features/qt_functions.prf:
../../qt/6.1.1/mingw81_64/mkspecs/features/qt_config.prf:
../../qt/6.1.1/mingw81_64/mkspecs/win32-g++/qmake.conf:
../../qt/6.1.1/mingw81_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../../qt/6.1.1/mingw81_64/mkspecs/features/exclusive_builds.prf:
../../qt/6.1.1/mingw81_64/mkspecs/features/toolchain.prf:
../../qt/6.1.1/mingw81_64/mkspecs/features/default_pre.prf:
../../qt/6.1.1/mingw81_64/mkspecs/features/win32/default_pre.prf:
../../qt/6.1.1/mingw81_64/mkspecs/features/resolve_config.prf:
../../qt/6.1.1/mingw81_64/mkspecs/features/exclusive_builds_post.prf:
../../qt/6.1.1/mingw81_64/mkspecs/features/default_post.prf:
../../qt/6.1.1/mingw81_64/mkspecs/features/qml_debug.prf:
../../qt/6.1.1/mingw81_64/mkspecs/features/entrypoint.prf:
../../qt/6.1.1/mingw81_64/mkspecs/features/precompile_header.prf:
../../qt/6.1.1/mingw81_64/mkspecs/features/warn_on.prf:
../../qt/6.1.1/mingw81_64/mkspecs/features/qmake_use.prf:
../../qt/6.1.1/mingw81_64/mkspecs/features/file_copies.prf:
../../qt/6.1.1/mingw81_64/mkspecs/features/win32/windows.prf:
../../qt/6.1.1/mingw81_64/mkspecs/features/testcase_targets.prf:
../../qt/6.1.1/mingw81_64/mkspecs/features/exceptions.prf:
../../qt/6.1.1/mingw81_64/mkspecs/features/yacc.prf:
../../qt/6.1.1/mingw81_64/mkspecs/features/lex.prf:
Hotels.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile Hotels.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug"

qmake_all: sub-InformationHotels-qmake_all sub-objects-qmake_all FORCE

make_first: sub-InformationHotels-make_first sub-objects-make_first  FORCE
all: sub-InformationHotels-all sub-objects-all  FORCE
clean: sub-InformationHotels-clean sub-objects-clean  FORCE
distclean: sub-InformationHotels-distclean sub-objects-distclean  FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) .qmake.stash
install_subtargets: sub-InformationHotels-install_subtargets sub-objects-install_subtargets FORCE
uninstall_subtargets: sub-InformationHotels-uninstall_subtargets sub-objects-uninstall_subtargets FORCE

sub-InformationHotels-debug:
	@if not exist InformationHotels\ mkdir InformationHotels\ & if not exist InformationHotels\ exit 1
	cd InformationHotels\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\projects\Hotels\InformationHotels\InformationHotels.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile debug
sub-objects-debug:
	@if not exist objects\ mkdir objects\ & if not exist objects\ exit 1
	cd objects\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\projects\Hotels\objects\objects.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile debug
debug: sub-InformationHotels-debug sub-objects-debug

sub-InformationHotels-release:
	@if not exist InformationHotels\ mkdir InformationHotels\ & if not exist InformationHotels\ exit 1
	cd InformationHotels\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\projects\Hotels\InformationHotels\InformationHotels.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile release
sub-objects-release:
	@if not exist objects\ mkdir objects\ & if not exist objects\ exit 1
	cd objects\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\projects\Hotels\objects\objects.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile release
release: sub-InformationHotels-release sub-objects-release

sub-InformationHotels-check:
	@if not exist InformationHotels\ mkdir InformationHotels\ & if not exist InformationHotels\ exit 1
	cd InformationHotels\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\projects\Hotels\InformationHotels\InformationHotels.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile check
sub-objects-check:
	@if not exist objects\ mkdir objects\ & if not exist objects\ exit 1
	cd objects\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\projects\Hotels\objects\objects.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile check
check: sub-InformationHotels-check sub-objects-check

sub-InformationHotels-benchmark:
	@if not exist InformationHotels\ mkdir InformationHotels\ & if not exist InformationHotels\ exit 1
	cd InformationHotels\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\projects\Hotels\InformationHotels\InformationHotels.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile benchmark
sub-objects-benchmark:
	@if not exist objects\ mkdir objects\ & if not exist objects\ exit 1
	cd objects\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\projects\Hotels\objects\objects.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile benchmark
benchmark: sub-InformationHotels-benchmark sub-objects-benchmark
install:install_subtargets  FORCE

uninstall: uninstall_subtargets FORCE

FORCE:

