#ifndef INFORMATIONHOTELS_GLOBAL_H
#define INFORMATIONHOTELS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(INFORMATIONHOTELS_LIBRARY)
#  define INFORMATIONHOTELS_EXPORT Q_DECL_EXPORT
#else
#  define INFORMATIONHOTELS_EXPORT Q_DECL_IMPORT
#endif

#endif // INFORMATIONHOTELS_GLOBAL_H
