#ifndef INFORMATIONAPARTMENTS_GLOBAL_H
#define INFORMATIONAPARTMENTS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(INFORMATIONAPARTMENTS_LIBRARY)
#  define INFORMATIONAPARTMENTS_EXPORT Q_DECL_EXPORT
#else
#  define INFORMATIONAPARTMENTS_EXPORT Q_DECL_IMPORT
#endif

#endif // INFORMATIONAPARTMENTS_GLOBAL_H
